### ISSUE TITLE
Vite: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by g0shed** [tailwindlabs/tailwindcss-jit#38] opened 2021-03-15 23:06 UTC
getting this error on a existing Vite project, already tried to disable plugins, and tw configuration but the error persists,

Cannot read property 'length' of undefined
    at posToNumber ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:4037:27)
    at generateCodeFrame ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:4062:13)
    at formatError ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:43479:42)
    at TransformContext.error ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:43438:19)
    at Object.transform ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:43643:25)
    at async transformRequest ([dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:59299:29)
    at async [dir]/node_modules/vite/dist/node/chunks/dep-6f1d3d8c.js:59407:32

**Comment by kwesterfeld2** [comment] 2021-03-16 11:03
Saw this exact issue as well.  The stacktrace is more helpful if you run "vite build", but I was unable to narrow down where in my css this error was coming from.

**Comment by adamwathan** [comment] 2021-03-16 11:06
Hey! Please provide a reproduction, it's totally impossible to know what to fix if we can't see the code causing the error 👀

**Comment by g0shed** [comment] 2021-03-16 11:48
@adamwathan the issue is related to layer components, somehow those are not working and thanks to @kwesterfeld2 I managed to debug a bit more and get more information by doing a vite build (ty btw)

**Comment by adamwathan** [comment] 2021-03-16 11:50
Can you provide a reproduction though? Like a repository that when I clone it and run it exhibits the error? I can't do anything without being able to see the error and debug the code.

**Comment by kwesterfeld2** [comment] 2021-03-16 16:11
I got this slightly different error location: 

```
Cannot read property 'length' of undefined
    at posToNumber (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:3201:27)
    at generateCodeFrame (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:3226:13)
    at formatError (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:45866:42)
    at TransformContext.error (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:45825:19)
    at Object.transform (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:46030:25)
    at async transformRequest (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:61624:29)
    at async /Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/dist/node/chunks/dep-1bdbec90.js:61732:32

```

Running a `vite build` results in a different error, and indeed it seems to be a layer issue where my css file does a css class like this: 

```
.yb-border-content {
  @apply foo bar etc;
}
```

And my vue component style:

```
<style lang="postcss" scoped>
@include "../main.css";

.some-other-thing {
  @apply yb-border-content;
}
```

And if I do `vite build` here, I get this: 

```
[vite:css] /Users/kwesterfeld/src/yb/ybcs/ui/src/app/query/Content.vue?vue&type=style&index=0&scoped=true&lang.postcss:725:3: The `yb-border-content` class does not exist. If `yb-border-content` is a custom class, make sure it is defined within a `@layer` directive.
file: /Users/kwesterfeld/src/yb/ybcs/ui/src/app/query/Content.vue?vue&type=style&index=0&scoped=true&lang.postcss
error during build:
CssSyntaxError: /Users/kwesterfeld/src/yb/ybcs/ui/src/app/query/Content.vue?vue&type=style&index=0&scoped=true&lang.postcss:725:3: The `yb-border-content` class does not exist. If `yb-border-content` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/node_modules/postcss/lib/input.js:113:16)
    at AtRule.error (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/vite/node_modules/postcss/lib/node.js:59:32)
    at /Users/kwesterfeld/src/yb/ybcs/ui/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:105:25
    at LazyResult.runOnRoot (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/Users/kwesterfeld/src/yb/ybcs/ui/node_modules/postcss/lib/lazy-result.js:190:17)
```

Not sure the build order is the same in these two cases, and not sure they correlate.

**Comment by g0shed** [comment] 2021-03-17 09:36
@adamwathan sorry for the delay, actually @kwesterfeld2 explained much better what was happening exactly using the @apply with a previous declares class doesn't work anymore with JIT, works fine with TW tho

**Comment by adamwathan** [comment] 2021-03-17 10:12
Gotcha! This is the recursive `@apply` limitation captured here: https://github.com/tailwindlabs/tailwindcss-jit/issues/66

Will close this one and we can track progress there 👍🏻

**Closed by adamwathan** 2021-03-17 10:12 UTC
