### ISSUE TITLE
Cannot have a space in a project folder name when using with Vite

### ISSUE THREAD

**Issue by web2033** [tailwindlabs/tailwindcss-jit#52] opened 2021-03-16 08:32 UTC
With this mode enabled I can't use any special chars in a project's folder name on Windows.
Example - https://github.com/web2033/vite-vue3-tailwind-starter

`project name` won't work, whereas
`project-name` will work

**Comment by laymonage** [comment] 2021-03-16 10:44
See https://github.com/tailwindlabs/tailwindcss-jit/issues/22.

**Comment by web2033** [comment] 2021-03-17 19:25
![2021-03-17_210952](https://user-images.githubusercontent.com/11320080/111526272-34136680-8767-11eb-9732-ff145e2a9530.png)

**Comment by bradlc** [comment] 2021-03-19 12:57
Going to close this as a duplicate of #22 👍

**Closed by bradlc** 2021-03-19 12:57 UTC
