### ISSUE TITLE
Arbitrary grid class not work use Next.js

### ISSUE THREAD

**Issue by vunamhung** [tailwindlabs/tailwindcss-jit#63] opened 2021-03-16 13:29 UTC
I have a bug with arbitrary grid class. I use lg:grid-cols-[3fr,1fr] and it work fine on local but when I deploy code on vercel.com, class not work.
This is my website
https://apato-website-git-develop-vunamhung.vercel.app/careers

**Comment by adamwathan** [comment] 2021-03-16 15:26
Hmm weird, I wonder if it's related to this seemingly custom CSS rule?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/4323180/111334980-64b1ae00-864a-11eb-9b0f-8d1629d591a6.png">


Can you create a real project on GitHub that reproduces so we can test?

**Comment by wKovacs64** [comment] 2021-03-16 16:47
I logged #45 earlier (with full reproduction), probably the same thing?

**Comment by adamwathan** [comment] 2021-03-16 19:48
Closing as duplicate of #45, let's track this there!

**Closed by adamwathan** 2021-03-16 19:48 UTC
