### ISSUE TITLE
JIT does not work with Snowpack http://snowpack.dev

### ISSUE THREAD

**Issue by verbose9** [tailwindlabs/tailwindcss-jit#181] opened 2021-03-29 06:24 UTC
### What version of @tailwindcss/jit are you using?

0.1.17

### What version of Node.js are you using?

14.x LTS

### What browser are you using?

Chrome, Microsoft Edge Chromium

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/verbose9/tlwind

Snowpack only takes up all of the class when the server start and never reloads.
Possible reason might be: Snowpack caches everything indefinitely.

Steps to reproduce:
Clone the repo [https://github.com/verbose9/tlwind](https://github.com/verbose9/tlwind) and `npm i` then `npm run dev`

**Comment by adamwathan** [comment] 2021-03-29 13:15
Hey! This is a duplicate of #126, will track there.

**Closed by adamwathan** 2021-03-29 13:15 UTC
