### ISSUE TITLE
css-loader can't handle paths with spaces

### ISSUE THREAD

**Issue by rolandleth** [tailwindlabs/tailwindcss-jit#22] opened 2021-03-15 18:34 UTC
Hey!

If the project is in a folder that has a space in its name anywhere along the path, css-loader breaks, but without spaces it works (that should teach me for using spaces, I know 😅):

```sh
Error: ENOENT: no such file or directory, stat '/Users/home/Some%20Projects/a-project/src/styles/index.css'
# or
Error: ENOENT: no such file or directory, stat '/Users/home/Some%20Projects/a-project/tailwind.config.js'
```

Using `tailwindcss` in `postcss.config.js` also works properly, with and without spaces.

The same thing happens in any kind of project (reproduced it in Next.js, and in razzle.js).

**Comment by tauzN** [comment] 2021-03-15 18:48
This might be related: https://github.com/tailwindlabs/tailwindcss-jit/issues/18

**Comment by rolandleth** [comment] 2021-03-15 18:56
It looks like it is, so it might not be  Vite-related, after all. In which case, we have another type of project that confirms the bug.

**Comment by bymayo** [comment] 2021-03-15 21:24
I also get the `ENOENT: no such file or directory, stat issue`, running it through Gulp / PostCSS

**Comment by johnnytest4real** [comment] 2021-03-16 01:39
Yep, had this same issue using Laravel Mix:

https://gist.github.com/johnnytest4real/6036e55bee447c2cc9b774a67b1345e0

**Comment by z-x** [comment] 2021-03-16 07:40
Confirmed on Windows and a very basic config. Directories with spaces doesn't work.

**Comment by surjithctly** [comment] 2021-03-17 06:45
Yes, I confirm this issue. 

Windows, Node 14.16.0.

Although, it doesn't work for me even after that because of the Infinite loop error in next.js

**Comment by anuraghazra** [comment] 2021-03-17 13:17
So the issue is with these two lines

https://github.com/tailwindlabs/tailwindcss-jit/blob/dfb1a3d253a710a538cfe7c5fd2c790a5df9c427/src/lib/setupContext.js#L186-L187

Can be fixed by decoding the URI

```js
    let pathname = url.parse(file).pathname
    let newModified = fs.statSync(decodeURIComponent(pathname)).mtimeMs
```

Or by just by passing the `file` in fs.statSync

```js
    let newModified = fs.statSync(file).mtimeMs
```

**Comment by surjithctly** [comment] 2021-03-17 14:42
@anuraghazra Great. I think you can create a pull-request with your proposal maybe? 

So, you can discuss this with the official team.

**Closed** 2021-03-19 18:36 UTC
