### ISSUE TITLE
[Snowpack][Svelte] @snowpack/plugin-svelte complains no selector for animate-xxx classes 

### ISSUE THREAD

**Issue by LBrian** [tailwindlabs/tailwindcss-jit#103] opened 2021-03-18 00:01 UTC
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/LBrian/direction-aware-ui

Just simply add `animate-ping` in `App.svelte` then it will trigger the issue

![image](https://user-images.githubusercontent.com/3888780/111553792-2ac2e200-87d9-11eb-90b9-11be5db8d191.png)

![Screen Shot 2021-03-18 at 10 45 47 am](https://user-images.githubusercontent.com/3888780/111553719-0ff06d80-87d9-11eb-9b83-34dd4f9992bc.png)

**Comment by bradlc** [comment] 2021-03-19 17:13
Thanks for reporting @LBrian! It looks like this is a duplicate of #94 👍

**Closed by bradlc** 2021-03-19 17:13 UTC
