### ISSUE TITLE
Focus Ring variables aren't compiled

### ISSUE THREAD

**Issue by robertgorbul** [tailwindlabs/tailwindcss-jit#131] opened 2021-03-21 14:45 UTC
### What version of @tailwindcss/jit are you using?

v0.1.5

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

elementaryOS(Linux)

### Reproduction repository

https://github.com/robertgorbul/detectify-coding-challenge/tree/feature/tailwind-jit

After switching to `@tailwindcss/jit` on Next.js, TailwindCSS project there're missing `-tw-ring-*` variables in dev mode (without purgecss)
![Screenshot from 2021-03-21 17-16-34](https://user-images.githubusercontent.com/9195693/111908245-8c997b00-8a69-11eb-971e-08e7ae7e0879.png)

**Comment by adamwathan** [comment] 2021-03-22 13:17
Hey! Sorry I can't really figure out what you mean, the repository you provided is way too big/complex for me to get set up and find the issue, but when I created my own project to test this out with Next, the `focus:ring` utilities work as I'd expect. I'm not sure what I should be looking at in your screenshot — it looks like all the classes are there with the correct CSS rules.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/4323180/111994944-c2cd0e00-8aee-11eb-99ef-282c1887bbdb.png">

Going to close this because it appears to work as expected, but if this is still an issue for you please create a new issue that includes an isolated reproduction rather than a full project, as well as a complete description of the problem so I better understand what's being reported. I'm not sure what you mean by missing variables as the variables look like they are present in your screenshot. Sorry if I'm missing something obvious 🤦

**Closed by adamwathan** 2021-03-22 13:17 UTC

**Comment by robertgorbul** [comment] 2021-03-22 18:55
Thanks for your response. I will try to investigate more and get back to you if I find anything helpful.
Basically when I'm switching to JIT those variables are missing for some reason:
![image](https://user-images.githubusercontent.com/9195693/112042404-8635fc80-8b58-11eb-872e-b4a1e4944a79.png)
In my first screenshot you can see that Firefox is greying them out and warns that those variables aren't set.
