### ISSUE TITLE
Loading `@tailwindcss/forms` seems to cause a PostCSS error (next.js)

### ISSUE THREAD

**Issue by christofferberg** [tailwindlabs/tailwindcss-jit#59] opened 2021-03-16 11:46 UTC
Repo: https://github.com/christofferberg/jit/tree/main/

I've tried to setup Tailwind JIT in a Nextjs project and everything seems to work fine, until I require `@tailwindcss/forms` in the plugins array of the `tailwind.config.js` file. 

Error:
```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.1.7, but postcss-preset-env uses 7.0.35. Perhaps this is the source of the error below.
error - ./styles/globals.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-6-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/globals.css)
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
``` 

`tailwind.config.js`:
```
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/forms"), // Loading this creates error: Unknown error from PostCSS plugin. Your current PostCSS version is 8.1.7, but postcss-preset-env uses 7.0.35. Perhaps this is the source of the error below.
    require("@tailwindcss/typography"),
    require("tailwindcss-debug-screens"),
  ],
};
```

`postcss.config.js`
```
module.exports = {
  plugins: [
    "@tailwindcss/jit",
    "postcss-nesting",
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
  ],
};
```

**Comment by sinnbeck** [comment] 2021-03-16 12:47
Isnt this just post-preset-env that hasn't been updated to postcss 8 yet?

https://github.com/csstools/postcss-preset-env/issues/191

**Comment by xCloudzx** [comment] 2021-03-16 13:23
@sinnbeck Looks like they updated yesterday: https://github.com/csstools/postcss-env-function/pull/11. I'd make sure you're on the latest version.

**Comment by calebmer** [comment] 2021-03-16 15:09
I’m also seeing this error. Removing `postcss-preset-env` does fix the error for me, but when I replace it with just `autoprefixer` the error comes back:

```
error - ./client/styles/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./client/styles/tailwind.css)
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
```

This time without the `postcss-preset-env` error message.

**Comment by adamwathan** [comment] 2021-03-16 15:19
Hey! This is the same issue as here ultimately:

https://github.com/tailwindlabs/tailwindcss-jit/issues/29

It's a bug somewhere that is resolved by updating to the latest version of autoprefixer. The issue is postcss-preset-env bundles autoprefixer internally, and postcss-preset-env is on old versions of everything.

I would recommend not using postcss-preset-env for now until it is updated (if it is), and instead just pulling in any PostCSS plugins you need independently so you can control which version is used more easily.

**Closed by adamwathan** 2021-03-16 15:19 UTC
